# Generated by Django 5.1.7 on 2025-03-24 12:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/demo/image/upload/v1/default_cl3qsg.jpg', max_length=255, verbose_name='image'),
        ),
    ]
