# Generated by Django 5.1.7 on 2025-03-29 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0004_alter_profile_image_expensecategory_expense_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('upcoming', 'Upcoming'), ('due', 'Due'), ('cancelled', 'Cancelled')], default='current', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('due_date', 'Due'), ('general', 'General')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
