# Generated by Django 5.1.7 on 2025-03-30 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0005_alter_subscriptions_status_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('frequency', models.CharField(default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('current', 'Current'), ('upcoming', 'Upcoming'), ('due', 'Due'), ('cancelled', 'Cancelled'), ('cancel_pending', 'Cancel Pending')], default='current', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
