# Generated by Django 5.1.7 on 2025-04-07 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0006_subscription_delete_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.CreateModel(
            name='SubsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subs', to='financeApp.subscategory'),
            preserve_default=False,
        ),
    ]
