# Generated by Django 5.1.7 on 2025-04-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeApp', '0009_savingsgoal_savingscontribution_delete_savings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='income_categories',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavingsContribution',
        ),
        migrations.DeleteModel(
            name='SavingsGoal',
        ),
    ]
